version: '3.8'

services:
  sglman:
    build: .
    image: sglman:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.18.0.1"
    restart: unless-stopped
    # Uncomment if you want to mount local files
    # volumes:
    #   - ./data:/app/data
