from theme.dialog.approve_crew_dialog import ApproveCrewDialog
from theme.dialog.confirmation_dialog import ConfirmationDialog
from theme.dialog.feedback_dialog import FeedbackDialog
from theme.dialog.match_result_dialog import MatchResultDialog
from theme.dialog.send_message_dialog import SendMessageDialog
from theme.dialog.station_assignment_dialog import StationAssignmentDialog
from theme.dialog.tournament_edit_dialog import TournamentDialog
from theme.dialog.user_edit_dialog import UserDialog, AdminUserDialog
