#!/usr/bin/env python3
"""
PostToolUse hook: flag a Write/Edit that leaves a .py file over the length budget.

Runs *after* the file is on disk, so it measures the real result of both a
whole-file Write and a fragment Edit. Two tiers: past SOFT_LIMIT it prints an
advisory, past HARD_LIMIT it prints a stronger "must split" message. Both exit 2
so Claude Code surfaces the note to the model (PostToolUse cannot prevent the
write that already happened). Anything else — non-Python, generated migration,
unreadable file, within budget — exits 0 (fail open).
"""

import json
import sys

SOFT_LIMIT = 800
HARD_LIMIT = 1500


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    file_path = tool_input.get("file_path", "")

    if not file_path or not file_path.endswith(".py"):
        sys.exit(0)

    normalized = file_path.replace("\\", "/")

    # migrations/ is auto-generated by aerich — not hand-maintained, skip it.
    if "migrations/" in normalized:
        sys.exit(0)

    # models.py is a known-oversized aggregate module; splitting it is tracked as
    # separate follow-up work, so suppress the advisory here to cut the noise.
    if normalized.endswith("/models.py") or normalized == "models.py":
        sys.exit(0)

    try:
        with open(file_path, "r", encoding="utf-8") as fh:
            lines = sum(1 for _ in fh)
    except OSError:
        sys.exit(0)

    if lines > HARD_LIMIT:
        print(
            f"FILE TOO LONG: '{file_path}' is {lines} lines, exceeding the hard "
            f"cap of {HARD_LIMIT}.\n"
            f"  This file must be split into smaller modules — extract cohesive "
            f"pieces along the three-layer pattern (docs/refactoring-guide.md).",
            file=sys.stderr,
        )
        sys.exit(2)

    if lines > SOFT_LIMIT:
        print(
            f"LONG FILE: '{file_path}' is {lines} lines, exceeding the "
            f"{SOFT_LIMIT}-line guideline.\n"
            f"  Consider splitting it into smaller modules "
            f"(docs/refactoring-guide.md) before it grows further.",
            file=sys.stderr,
        )
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
