#!/usr/bin/env python3
"""
PreToolUse hook: protect aerich-generated migrations from hand-edits.

Files under `migrations/models/` are generated by `aerich migrate`. Editing them
by hand desyncs them from `models.py` and the aerich version table. Reads a
Claude Code tool payload from stdin and exits with:
  0 — no violation (or not applicable)
  2 — the target is a generated migration (stderr explains the right workflow)
"""

import json
import sys


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    tool_name = payload.get("tool_name", "")
    if tool_name not in ("Write", "Edit"):
        sys.exit(0)

    file_path = payload.get("tool_input", {}).get("file_path", "")
    if not file_path:
        sys.exit(0)

    norm = file_path.replace("\\", "/")
    if "/migrations/models/" in norm or norm.startswith("migrations/models/"):
        print(
            f"MIGRATION SAFETY VIOLATION in '{file_path}':\n"
            f"  This file is generated by aerich and must not be hand-edited.\n"
            f"  Fix: change models.py, then run `poetry run aerich migrate && poetry run aerich upgrade`.",
            file=sys.stderr,
        )
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
