"""Async qualifier — the run-expiry half of the run lifecycle.

A run is created ``IN_PROGRESS`` the moment a player draws a permalink, and
nothing in the self-paced flow requires them to come back. Left alone, an
abandoned run holds its permalink assignment and the player's pool slot
indefinitely, keeps counting toward draw fairness, and — because a claimed finish
time is only sanity-checked against the wall clock since the draw
(:func:`~application.services.async_qualifier.async_qualifier_rules.classify_claim`)
— leaves an ever-widening window in which any finish time is claimable.

So a run gets a deadline: one warning DM ahead of it, then an automatic forfeit.
Both are recoverable — a reviewer can grant a reattempt — and both are attributed
to the runner rather than to a staff member, because no human made this decision.

Split out of :class:`AsyncQualifierService` as a mixin (the sibling of
``PlayerReadsMixin``) to keep that module inside the file-length guideline. The
worker in :mod:`application.services.async_qualifier.async_qualifier_worker`
drives these; nothing else should.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Awaitable, Callable, Optional

from application.events import EventType
from application.feature_flags import requires_feature
from application.services.async_qualifier import async_qualifier_notifications as notifications
from application.services.async_qualifier import async_qualifier_rules as rules
from application.services.audit_service import AuditActions
from models import (
    AsyncQualifier,
    AsyncQualifierReviewStatus,
    AsyncQualifierRun,
    AsyncQualifierRunStatus,
    FeatureFlag,
    User,
)

if TYPE_CHECKING:  # typing only — importing these at runtime would cycle
    from application.repositories import AsyncQualifierRunRepository
    from application.services.audit_service import AuditService


class RunExpiryMixin:
    """Expire abandoned runs, and warn before doing so.

    The three members below are supplied by :class:`AsyncQualifierService`, which
    composes this mixin. They are *declared* (annotation only, no assignment, so
    nothing shadows the real ones at runtime) to state the contract a composer
    must satisfy rather than leaving it implicit in the attribute accesses.
    """

    run_repository: 'AsyncQualifierRunRepository'
    audit_service: 'AuditService'
    _require_qualifier: Callable[[int], Awaitable[AsyncQualifier]]

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def expire_run(
        self,
        run: AsyncQualifierRun,
        *,
        actor: Optional[User] = None,
        now: Optional[datetime] = None,
    ) -> AsyncQualifierRun:
        """Forfeit an in-progress run that sat open past its qualifier's limit.

        The system's counterpart to ``forfeit_run``: the same terminal state and
        the same zero score — a run with no finish time did not finish — but
        ``expired_at`` records that nobody *chose* it, which is the distinction an
        appeal and the runner's own view need. A reviewer can still grant a
        reattempt, so this is recoverable rather than punitive.

        Idempotent: a run that has already left ``IN_PROGRESS`` is returned
        untouched, so a worker retry after a partial tick cannot double-forfeit.
        """
        if run.status != AsyncQualifierRunStatus.IN_PROGRESS:
            return run
        now = now or datetime.now(timezone.utc)
        # ``<fk>_id`` is generated by Tortoise at runtime and invisible to mypy;
        # the ignores below are that false positive, not a missing attribute.
        qualifier = await self._require_qualifier(run.qualifier_id)  # type: ignore[attr-defined]
        limit_hours = int(rules.run_time_limit(qualifier).total_seconds() // 3600)
        run = await self.run_repository.update(
            run,
            status=AsyncQualifierRunStatus.FORFEIT,
            finished_at=now,
            expired_at=now,
            score=0.0,
            review_status=AsyncQualifierReviewStatus.APPROVED,
            measured_seconds=rules.measure_elapsed(run.started_at, now),
        )
        # Attributed to the runner, not to a staff member: the audit trail should
        # not imply an organiser forfeited someone's run.
        actor = actor or await run.user
        await self.audit_service.write_and_publish(
            actor, AuditActions.ASYNC_QUALIFIER_RUN_EXPIRED,
            {'run_id': run.id, 'qualifier_id': run.qualifier_id,  # type: ignore[attr-defined]
             'user_id': run.user_id, 'limit_hours': limit_hours},  # type: ignore[attr-defined]
            EventType.ASYNC_QUALIFIER_RUN_EXPIRED,
            event_details={
                'run_id': run.id, 'qualifier_id': run.qualifier_id,  # type: ignore[attr-defined]
                'user_id': run.user_id,  # type: ignore[attr-defined]
            },
        )
        await notifications.notify_run_expired(run, limit_hours)
        return run

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def warn_run_expiring(
        self,
        run: AsyncQualifierRun,
        deadline: datetime,
        *,
        now: Optional[datetime] = None,
    ) -> AsyncQualifierRun:
        """Send the one pre-expiry warning for a run, and stamp it as sent.

        Stamped **before** the DM goes out (the volunteer reminder's rule): a
        delivery failure or a restart mid-send must not turn one warning into one
        per tick.
        """
        if run.expiry_warned_at is not None:
            return run
        run = await self.run_repository.update(
            run, expiry_warned_at=now or datetime.now(timezone.utc),
        )
        await notifications.notify_run_expiring(run, deadline)
        return run
