"""Async qualifier — the run-expiry half of the run lifecycle.

A run is created ``IN_PROGRESS`` the moment a player draws a permalink, and
nothing in the self-paced flow requires them to come back. Left alone, an
abandoned run holds its permalink assignment and the player's pool slot
indefinitely, keeps counting toward draw fairness, and — because a claimed finish
time is only sanity-checked against the wall clock since the draw
(:func:`~application.services.async_qualifier.async_qualifier_rules.classify_claim`)
— leaves an ever-widening window in which any finish time is claimable.

So a run gets a deadline: one warning DM ahead of it, then an automatic forfeit.
Both are recoverable — a reviewer can grant a reattempt — and both are attributed
to the runner rather than to a staff member, because no human made this decision.

Split out of :class:`AsyncQualifierService` as a mixin (the sibling of
``PlayerReadsMixin``) to keep that module inside the file-length guideline. The
worker in :mod:`application.services.async_qualifier.async_qualifier_worker`
drives these; nothing else should.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Awaitable, Callable, Optional

from application.events import EventType
from application.feature_flags import requires_feature
from application.services.async_qualifier import async_qualifier_notifications as notifications
from application.services.async_qualifier import async_qualifier_rules as rules
from application.services.audit_service import AuditActions
from models import (
    AsyncQualifier,
    AsyncQualifierReviewStatus,
    AsyncQualifierRun,
    AsyncQualifierRunStatus,
    FeatureFlag,
    Role,
    User,
)

if TYPE_CHECKING:  # typing only — importing these at runtime would cycle
    from application.repositories import AsyncQualifierRepository, AsyncQualifierRunRepository
    from application.services.audit_service import AuditService


def _aware(value: datetime) -> datetime:
    """Naive datetimes are stored as UTC, so read them back that way."""
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


class RunExpiryMixin:
    """Expire abandoned runs, and warn before doing so.

    The three members below are supplied by :class:`AsyncQualifierService`, which
    composes this mixin. They are *declared* (annotation only, no assignment, so
    nothing shadows the real ones at runtime) to state the contract a composer
    must satisfy rather than leaving it implicit in the attribute accesses.
    """

    repository: 'AsyncQualifierRepository'
    run_repository: 'AsyncQualifierRunRepository'
    audit_service: 'AuditService'
    _require_qualifier: Callable[[int], Awaitable[AsyncQualifier]]

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def expire_run(
        self,
        run: AsyncQualifierRun,
        *,
        actor: Optional[User] = None,
        now: Optional[datetime] = None,
    ) -> AsyncQualifierRun:
        """Forfeit an in-progress run that sat open past its qualifier's limit.

        The system's counterpart to ``forfeit_run``: the same terminal state and
        the same zero score — a run with no finish time did not finish — but
        ``expired_at`` records that nobody *chose* it, which is the distinction an
        appeal and the runner's own view need. A reviewer can still grant a
        reattempt, so this is recoverable rather than punitive.

        Idempotent: a run that has already left ``IN_PROGRESS`` is returned
        untouched, so a worker retry after a partial tick cannot double-forfeit.
        """
        if run.status != AsyncQualifierRunStatus.IN_PROGRESS:
            return run
        now = now or datetime.now(timezone.utc)
        # ``<fk>_id`` is generated by Tortoise at runtime and invisible to mypy;
        # the ignores below are that false positive, not a missing attribute.
        qualifier = await self._require_qualifier(run.qualifier_id)  # type: ignore[attr-defined]
        limit_hours = int(rules.run_time_limit(qualifier).total_seconds() // 3600)
        run = await self.run_repository.update(
            run,
            status=AsyncQualifierRunStatus.FORFEIT,
            finished_at=now,
            expired_at=now,
            score=0.0,
            review_status=AsyncQualifierReviewStatus.APPROVED,
            measured_seconds=rules.measure_elapsed(run.started_at, now),
        )
        # Attributed to the runner, not to a staff member: the audit trail should
        # not imply an organiser forfeited someone's run.
        actor = actor or await run.user
        await self.audit_service.write_and_publish(
            actor, AuditActions.ASYNC_QUALIFIER_RUN_EXPIRED,
            {'run_id': run.id, 'qualifier_id': run.qualifier_id,  # type: ignore[attr-defined]
             'user_id': run.user_id, 'limit_hours': limit_hours},  # type: ignore[attr-defined]
            EventType.ASYNC_QUALIFIER_RUN_EXPIRED,
            event_details={
                'run_id': run.id, 'qualifier_id': run.qualifier_id,  # type: ignore[attr-defined]
                'user_id': run.user_id,  # type: ignore[attr-defined]
            },
        )
        await notifications.notify_run_expired(run, limit_hours)
        return run

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def warn_run_expiring(
        self,
        run: AsyncQualifierRun,
        deadline: datetime,
        *,
        now: Optional[datetime] = None,
    ) -> AsyncQualifierRun:
        """Send the one pre-expiry warning for a run, and stamp it as sent.

        Stamped **before** the DM goes out (the volunteer reminder's rule): a
        delivery failure or a restart mid-send must not turn one warning into one
        per tick.
        """
        if run.expiry_warned_at is not None:
            return run
        run = await self.run_repository.update(
            run, expiry_warned_at=now or datetime.now(timezone.utc),
        )
        await notifications.notify_run_expiring(run, deadline)
        return run

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def notify_review_backlog(
        self, qualifier: AsyncQualifier, *, now: Optional[datetime] = None
    ) -> int:
        """Tell the reviewer set about a queue nobody has worked. DMs sent.

        The queue used to be pull-only: ``submit_run`` audits and publishes an
        event, and nothing reached a human — so the only way to discover work was
        to open the drill-down and look.

        Deliberately a backlog reminder rather than a DM per submission. Which
        people get it: the qualifier's own ``admins`` if it has any, else whoever
        holds ``QUALIFIER_ADMIN`` — the role that gates this surface. Not community
        STAFF at large, who can also review but have not taken it on.

        Stamps before sending, the same rule as the expiry warning: a delivery
        failure or a restart mid-send must not turn one reminder into one per tick.
        """
        now = now or datetime.now(timezone.utc)
        waiting, oldest = await self.run_repository.pending_review_backlog(qualifier.id)
        if not waiting or not rules.backlog_is_worth_reporting(
            oldest, qualifier.review_backlog_notified_at, now,
        ):
            return 0
        reviewers = await qualifier.admins.all()
        if not reviewers:
            from application.services.user_service import UserService
            reviewers = await UserService().get_community_people(
                role=Role.QUALIFIER_ADMIN, has_discord=True,
            )
        if not reviewers:
            # Nobody to tell. Left unstamped on purpose: the moment a reviewer is
            # added, they should hear about the backlog that was already there.
            return 0
        await self.repository.update(qualifier, review_backlog_notified_at=now)
        # ``oldest`` is non-None here: ``backlog_is_worth_reporting`` returns False
        # for a None one, which the guard above already acted on.
        hours = max(1, int((now - _aware(oldest)).total_seconds() // 3600))  # type: ignore[arg-type]
        return await notifications.notify_review_queue_waiting(
            reviewers, qualifier, waiting=waiting, oldest_hours=hours,
        )

    @requires_feature(FeatureFlag.ASYNC_QUALIFIERS)
    async def release_stale_claim(self, run: AsyncQualifierRun) -> AsyncQualifierRun:
        """Drop a review claim that has aged out, so the run returns to the queue.

        The counterpart of ``release_claim`` with no reviewer behind it: unaudited
        and un-notified, because nobody decided anything — a lock simply expired.
        Idempotent, so a run swept twice is a no-op rather than a second write.
        """
        if run.review_claimed_by_id is None:  # type: ignore[attr-defined]
            return run
        return await self.run_repository.update(
            run, review_claimed_by_id=None, review_claimed_at=None,
        )
